import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "ru";

const translations = {
  en: {
    // Navigation
    nav_execution_workspace: "Execution Workspace",
    nav_dashboard: "Dashboard",
    nav_journal: "Trade Journal",
    nav_replay: "Candle Replay",
    nav_statistics: "Performance Stats",
    nav_playbooks: "Playbooks & Rules",
    nav_playbooks_creator: "Playbooks Creator",
    nav_trading_plan: "Trading Risk Plan",
    nav_cognitive_tracker: "Cognitive Tracker",
    nav_auditable_goals: "Auditable Goals",
    nav_ai_engine: "Intelligent AI Engine",
    nav_ai_coach: "AI Workstation Coach",
    nav_ai_reviews: "AI Session Reviews",
    nav_integrations: "Integrations Port",
    nav_elite_account: "Elite Account",
    nav_cognitive_sync: "COGNITIVE SYNC ONLINE",
    workspace_path: "WORKSPACE PATH",

    // Dashboard
    db_total_pnl: "Total PnL",
    db_win_rate: "Win Rate",
    db_profit_factor: "Profit Factor",
    db_today_pnl: "Today's PnL",
    db_win_pnl: "Win PnL",
    db_total: "Total",
    db_elite_edge: "Elite Edge",
    db_moderate_edge: "Moderate Edge",
    db_negative_edge: "Negative Edge",
    db_weekly: "Weekly",
    db_monthly: "Monthly",
    db_avg_winner: "Avg Winner",
    db_avg_loser: "Avg Loser",
    db_avg_rr: "Avg Achieved R:R",
    db_expectancy: "Trading Expectancy",
    db_max_dd: "Max Drawdown",
    db_streak: "Win / Loss Streak",
    db_equity_curve: "Realized Equity Curve",
    db_equity_desc: "Cumulative performance growth tracker",
    db_sharpe: "Sharpe Ratio",
    db_pnl_dist: "PnL Distribution",
    db_pnl_dist_desc: "Frequency breakdown of trade returns",
    db_best_strat: "Best Strategy",
    db_worst_strat: "Worst Strategy",
    db_calendar: "Calendar Heatmap (June 2026)",
    db_calendar_desc: "Click any active trading day to audit execution checklists",
    db_legend_loss: "Loss",
    db_legend_gain: "Gain",
    db_insight_title: "AI Coach Insight",
    db_insight_text: "Your highest-edge setup this month is the VWAP Pullback Play on tech equities. However, early impulse FOMO entries on Nasdaq tickers represent a major profit leak ($408.00 lost). Click on the AI Coach tab to run a deep diagnostic.",
    db_launch_consultation: "Launch AI Consultation →",
    db_intraday_audit: "Intraday Journal Audit",
    db_close: "✕ Close",
    db_view_replay: "View Replay →",

    // Journal
    jr_search_placeholder: "Search symbol, setup, playbook...",
    jr_import: "Import",
    jr_export: "Export",
    jr_add_trade: "Add Trade",
    jr_all_assets: "All Assets",
    jr_stocks: "Stocks",
    jr_crypto: "Crypto",
    jr_forex: "Forex",
    jr_options: "Options",
    jr_futures: "Futures",
    jr_all_directions: "All Directions",
    jr_long: "Long",
    jr_short: "Short",
    jr_all_strategies: "All Strategies",
    jr_all_emotions: "All Emotions",
    jr_symbol_type: "SYMBOL / TYPE",
    jr_dir: "DIR",
    jr_entry_exit: "ENTRY / EXIT",
    jr_size: "SIZE",
    jr_net_pnl: "NET PNL",
    jr_rr: "R:R",
    jr_strategy: "STRATEGY",
    jr_rating: "RATING",
    jr_actions: "ACTIONS",
    jr_no_trades: "No trades match the current filter query. Try modifying search limits.",
    jr_log_new_trade: "LOG NEW TRADE EXECUTION",
    jr_symbol: "Symbol *",
    jr_asset_class: "Asset Class",
    jr_direction: "Direction",
    jr_entry_price: "Entry Price *",
    jr_exit_price: "Exit Price *",
    jr_position_size: "Position Size *",
    jr_stop_loss: "Stop Loss (Optional)",
    jr_take_profit: "Take Profit (Optional)",
    jr_strategy_playbook: "Strategy Playbook",
    jr_trading_style: "Trading Style",
    jr_intraday: "Day Trading (Intraday)",
    jr_swing: "Swing Trading",
    jr_intraday_desc: "Quick entries and exits within a single session. Focused on high liquidity, momentum, and strict daily risk limits.",
    jr_swing_desc: "Positions held for several days or weeks. Focused on medium-term trends, market cycles, and wider stop-losses.",
    jr_entry_timestamp: "Entry Timestamp",
    jr_exit_timestamp: "Exit Timestamp",
    jr_broker_account: "Broker Account",
    jr_emotion_before: "Emotion Before",
    jr_emotion_after: "Emotion After",
    jr_slippage_fees: "Slippage/Fees ($)",
    jr_commissions: "Commissions ($)",
    jr_confidence: "Confidence (1-5)",
    jr_execution_rating: "Execution Rating (1-5)",
    jr_visual_setup: "Visual Setup details",
    jr_psych_mistakes: "Psychological Mistakes Identified",
    jr_notes_reflections: "Trade Notes & Reflections",
    jr_actionable_lesson: "Actionable Lesson Learned",
    jr_tags_comma: "Tags (Comma-separated)",
    jr_screenshot: "Trade Screenshot",
    jr_upload_screenshot: "Upload Screenshot",
    jr_drag_screenshot: "Drag & drop a screenshot image (or click to select)",
    jr_remove_screenshot: "Remove Screenshot",
    jr_cancel: "Cancel",
    jr_save_trade: "Save Trade Log",
    jr_import_title: "IMPORT BROKER JOURNAL (CSV)",
    jr_import_desc: "Select your brokerage file (TradeZella, Binance, Bybit, Tradovate, Interactive Brokers Excel sheets) or use our fast auto-mapper.",
    jr_detected_formats: "Detected Formats",
    jr_drag_drop: "drag and drop broker export here",
    jr_supports: "supports .csv, .xlsx",
    jr_simulate_import: "Simulate Sample Import",
    jr_parsing: "Parsing broker logs... mapping parameters",
    jr_import_success: "✓ Import Successful! 2 new trade executions integrated.",
    jr_import_ready: "Ready to Import",
    jr_confirm_import: "Confirm Import",
    jr_clear: "Clear",
    jr_invalid_file: "Invalid File",

    // Candle Replay
    rp_title: "INTERACTIVE CANDLE REPLAY ENGINE",
    rp_subtitle: "Replay historical ticks candle-by-candle to audit execution discipline",
    rp_select_trade: "Select Trade to Replay",
    rp_no_trades: "No trades recorded yet. Go to Trade Journal to log a trade first!",
    rp_trade_specs: "Trade Specifications",
    rp_specs_direction: "Direction",
    rp_specs_entry: "Entry Price",
    rp_specs_exit: "Exit Price",
    rp_specs_pnl: "Realized PnL",
    rp_specs_rr: "Achieved R:R",
    rp_specs_stop: "Stop Loss",
    rp_specs_target: "Take Profit",
    rp_specs_strategy: "Strategy",
    rp_specs_emotions: "Emotions",
    rp_specs_notes: "Execution Notes",
    rp_controls: "Replay Controls",
    rp_ctrl_prev: "Previous",
    rp_ctrl_play: "Play Auto",
    rp_ctrl_pause: "Pause",
    rp_ctrl_next: "Next Candle",
    rp_ctrl_reset: "Reset",
    rp_ctrl_speed: "Speed",
    rp_candlestick_chart: "Candlestick Simulation Chart",
    rp_chart_legend_entry: "Entry Event",
    rp_chart_legend_exit: "Exit Event",
    rp_audit_logs: "Replay Audit Logs",
    rp_audit_start: "Candlestick replay initiated. Press Play or Next to cycle candles.",
    rp_audit_entry_alert: "CRITICAL: Entry trigger reached at candle index",
    rp_audit_exit_alert: "DISCIPLINE CHECK: Realized exit triggered at candle index",
    rp_audit_complete: "Simulation complete. Review execution metrics above.",
    rp_audit_consolidation: "Consolidating price action...",

    // Statistics
    st_title: "MULTIDIMENSIONAL TRADING STATS",
    st_subtitle: "Deep audit metrics of your mathematical edge and performance distribution",
    st_tab_overview: "Overview Metrics",
    st_tab_strategies: "Strategy Edge",
    st_tab_timeseries: "Time Frame Analysis",
    st_mathematical_edge: "Mathematical Edge Breakdown",
    st_win_pnl: "Total Profit from Wins",
    st_loss_pnl: "Total Loss from Losses",
    st_win_loss_ratio: "Win / Loss Ratio",
    st_expectancy_desc: "Expectancy is the average dollar amount you expect to win or lose per trade.",
    st_distribution_by_strategy: "PnL Distribution by Strategy",
    st_timeframe_distribution: "PnL Distribution by Days of Week",
    st_holding_time_title: "Trade Holding Time & Correlation",
    st_efficiency: "Execution Efficiency",

    // Playbooks
    pl_title: "STRATEGY PLAYBOOKS CREATOR",
    pl_subtitle: "Formalize high-fidelity setup constraints to prevent impulsive execution",
    pl_add_strategy: "Create Strategy Playbook",
    pl_target_rr: "Target R:R",
    pl_when_to_use: "When to Use (Market Conditions)",
    pl_when_not_to_use: "When NOT to Use (Banned Conditions)",
    pl_strict_checklist: "Strict Entry Checklist",
    pl_recent_trades: "Recent Executed Trades under",
    pl_no_trades: "No trades logged under this strategy yet",
    pl_form_title: "CONSTRUCT STRATEGIC PLAYBOOK",
    pl_form_name: "Strategy Name",
    pl_form_desc: "Description / Institutional Thesis",
    pl_form_checklist: "Checklist Rules (one per line)",
    pl_form_create: "Save Playbook Strategy",

    // Trading Plan
    tp_title: "STRICT AUDITABLE TRADING RISK PLAN",
    tp_subtitle: "Set hard mathematical boundaries. Breaking these triggers severe psychological coaching logs.",
    tp_edit: "Edit Parameters",
    tp_save: "Lock Risk Parameters",
    tp_daily_loss: "Daily Loss Limit",
    tp_max_trades: "Max Daily Trades",
    tp_banned_triggers: "Banned Action Triggers",
    tp_banned_desc: "Any trade matching these categories counts as a severe rule violation.",
    tp_entry_rules: "Mandatory Entry Criteria",
    tp_entry_desc: "Checklist that must be manually satisfied before entering any trade.",
    tp_exit_rules: "Mandatory Exit Guidelines",
    tp_exit_desc: "Rules governing targets, trailing stops, and manual emergency cuts.",
    tp_morning_prep: "Daily Morning Preparation Protocol",
    tp_evening_review: "Daily Evening Review Protocol",

    // Psychology
    ps_title: "COGNITIVE & MENTAL BALANCE TRACKER",
    ps_subtitle: "Track mental metrics to identify sleep-induced or greed-induced risk exposure",
    ps_log_button: "Log Daily Cognition",
    ps_cognitive_scores: "Cognitive & Stress Scores",
    ps_fomo_freq: "FOMO Frequency",
    ps_overtrading_score: "Overtrading Score",
    ps_sleep_quality: "Sleep Quality",
    ps_stress_level: "Stress Level",
    ps_energy_level: "Energy Level",
    ps_revenge_trading: "Revenge Trading Recorded?",
    ps_mental_journal: "Cognitive & Emotional Daily Journal",
    ps_log_title: "LOG DAILY COGNITIVE STATUS",
    ps_form_fomo: "FOMO Urge Intensity (1-5)",
    ps_form_overtrading: "Overtrading Impulse (1-5)",
    ps_form_fear: "Fear Intensity (1-5)",
    ps_form_greed: "Greed Intensity (1-5)",
    ps_form_patience: "Patience Level (1-5)",
    ps_form_sleep: "Sleep Duration & Depth (1-5)",
    ps_form_stress: "Stress/Anxiety Level (1-5)",
    ps_form_energy: "Physical Energy (1-5)",
    ps_form_revenge: "Did you engage in revenge trading today?",
    ps_form_notes: "Mental Notes & Emotional Reflections",
    ps_form_save: "Save Cognitive Log",

    // Goals
    gl_title: "AUDITABLE DISCIPLINE & PNL GOALS",
    gl_subtitle: "Create mathematical goals verified automatically by your journal database",
    gl_add: "Create Auditable Goal",
    gl_progress: "Goal Progress Overview",
    gl_form_title: "CONSTRUCT GOAL AUDIT TARGET",
    gl_form_name: "Goal Title / Target Name",
    gl_form_type: "Time Frame",
    gl_form_category: "Category Metric",
    gl_form_unit: "Unit Value",
    gl_form_target: "Target Numerical Value",
    gl_form_current: "Starting Numerical Value",
    gl_form_save: "Activate Goal Tracker",

    // AI Coach
    ac_title: "AI TRADING COACH WORKSTATION",
    ac_subtitle: "Interactive Cognitive Behavior Therapy (CBT) conversational agent for risk control",
    ac_prompt_fomo: "Analyze my FOMO patterns based on sleep",
    ac_prompt_rules: "Where am I leaking profits the most?",
    ac_prompt_patience: "Give me a patience checklist for TSLA",
    ac_chat_placeholder: "Describe a recent emotional trade or ask for a risk diagnostic...",
    ac_chat_send: "Consult Coach",

    // Reviews
    rv_title: "AI COGNITIVE SESSION REVIEWS",
    rv_subtitle: "Generate structured statistical and behavioral performance audits using Gemini",
    rv_card_daily: "Daily Review",
    rv_card_weekly: "Weekly Audit",
    rv_card_monthly: "Monthly Audit",
    rv_card_daily_desc: "Compile today's trades & psychological logs into an actionable CBT audit.",
    rv_card_weekly_desc: "Run multi-day variance checks, strategy leak analysis and performance curves.",
    rv_card_monthly_desc: "Synthesize long-term psychological flaws, expectancy, and strategic guidelines.",
    rv_generate_btn: "Generate Review",
    rv_generating: "Analyzing trade logs... compiling behavioral patterns",
    rv_title_report: "AI Generated Report",
    rv_report_score: "Discipline Score",

    // Settings
    se_title: "SECURE INTEGRATIONS & PROFILE SETTINGS",
    se_subtitle: "Configure real-time sync with global multi-broker standard endpoints",
    se_supported: "Supported Brokerages",
    se_link_port: "Link API Port for",
    se_connected: "CONNECTION ESTABLISHED",
    se_connected_desc: "ZellaTrader AI is listening to API transaction logs on",
    se_connected_desc_end: "Your execution updates are automatically parsed and imported into the Journal dashboard daily at 16:30 EST.",
    se_disconnect: "Disconnect Integration Port",
    se_syncing: "Synchronizing credentials... testing socket handshakes",
    se_token_prompt: "To import transactions securely, generate an API token or read-only read-leg authorization keys in your broker console.",
    se_api_key: "API Key / Client ID",
    se_api_secret: "API Secret / Secret Salt",
    se_key_warning: "All API keys are encrypted at-rest using high-grade AES-GCM standards. ZellaTrader requires only read-only transaction histories scopes; execution permissions are disabled.",
    se_auth_connect: "Authenticate & Connect Sync",
    se_lang_section: "Language Settings",
    se_lang_desc: "Select your preferred workspace interface language",
    se_tradovate_title: "Tradovate Broker Sync & Analysis",
    se_tradovate_help: "How to export Tradovate CSV/XLSX: Go to Reports -> Orders or Fills. Select Date Range, click Export as CSV. Ensure columns: Contract, Price, Qty, Timestamp are visible.",
    se_tradovate_connect: "Connect Tradovate API",
    se_tradovate_sync_btn: "Sync & Run AI Audit",
    se_tradovate_desc: "Connect your Tradovate workspace. Zella AI will automatically fetch your fills, pair them into closed trades, and perform a deep CBT psychological review."
  },
  ru: {
    // Navigation
    nav_execution_workspace: "Рабочее Пространство",
    nav_dashboard: "Панель приборов",
    nav_journal: "Журнал сделок",
    nav_replay: "Симулятор свечей",
    nav_statistics: "Статистика результатов",
    nav_playbooks: "Шаблоны и Правила",
    nav_playbooks_creator: "Конструктор шаблонов",
    nav_trading_plan: "Риск-план торговли",
    nav_cognitive_tracker: "Когнитивный трекер",
    nav_auditable_goals: "Проверяемые цели",
    nav_ai_engine: "Интеллектуальный ИИ-движок",
    nav_ai_coach: "ИИ-наставник сессии",
    nav_ai_reviews: "Обзоры сессий ИИ",
    nav_integrations: "Порт интеграций",
    nav_elite_account: "Элитный аккаунт",
    nav_cognitive_sync: "КОГНИТИВНАЯ СИНХРОНИЗАЦИЯ",
    workspace_path: "ПУТЬ К РАБОЧЕЙ ОБЛАСТИ",

    // Dashboard
    db_total_pnl: "Общий PnL",
    db_win_rate: "Процент побед",
    db_profit_factor: "Профит-фактор",
    db_today_pnl: "PnL за сегодня",
    db_win_pnl: "Прибыльный PnL",
    db_total: "Всего",
    db_elite_edge: "Элитное преимущество",
    db_moderate_edge: "Умеренное преимущество",
    db_negative_edge: "Отрицательное преимущество",
    db_weekly: "Недельный",
    db_monthly: "Месячный",
    db_avg_winner: "Ср. Выигравшая",
    db_avg_loser: "Ср. Проигравшая",
    db_avg_rr: "Ср. достигнутый R:R",
    db_expectancy: "Матожидание сделки",
    db_max_dd: "Макс. просадка",
    db_streak: "Серия побед / потерь",
    db_equity_curve: "Кривая реализованного капитала",
    db_equity_desc: "Совокупный трекер роста результатов",
    db_sharpe: "Коэффициент Шарпа",
    db_pnl_dist: "Распределение PnL",
    db_pnl_dist_desc: "Частотный анализ доходности сделок",
    db_best_strat: "Лучшая стратегия",
    db_worst_strat: "Худшая стратегия",
    db_calendar: "Тепловая карта календаря (Июнь 2026)",
    db_calendar_desc: "Нажмите на любой день, чтобы проверить контрольные списки исполнения",
    db_legend_loss: "Убыток",
    db_legend_gain: "Прибыль",
    db_insight_title: "Инсайт ИИ-наставника",
    db_insight_text: "Ваша наиболее прибыльная модель в этом месяце — VWAP Pullback Play на технологических акциях. Однако ранние импульсивные сделки (FOMO) на тикерах Nasdaq вызывают серьезную утечку прибыли (потеряно $408.00). Откройте вкладку ИИ-наставник, чтобы провести диагностику.",
    db_launch_consultation: "Начать консультацию с ИИ →",
    db_intraday_audit: "Внутридневной аудит журнала",
    db_close: "✕ Закрыть",
    db_view_replay: "Смотреть симуляцию →",

    // Journal
    jr_search_placeholder: "Поиск символа, сетапа, шаблона...",
    jr_import: "Импорт",
    jr_export: "Экспорт",
    jr_add_trade: "Добавить сделку",
    jr_all_assets: "Все активы",
    jr_stocks: "Акции",
    jr_crypto: "Крипта",
    jr_forex: "Форекс",
    jr_options: "Опционы",
    jr_futures: "Фьючерсы",
    jr_all_directions: "Все направления",
    jr_long: "Длинная (Long)",
    jr_short: "Короткая (Short)",
    jr_all_strategies: "Все стратегии",
    jr_all_emotions: "Все эмоции",
    jr_symbol_type: "СИМВОЛ / ТИП",
    jr_dir: "НАПР",
    jr_entry_exit: "ВХОД / ВЫХОД",
    jr_size: "РАЗМЕР",
    jr_net_pnl: "ЧИСТЫЙ PNL",
    jr_rr: "R:R",
    jr_strategy: "СТРАТЕГИЯ",
    jr_rating: "ОЦЕНКА",
    jr_actions: "ДЕЙСТВИЯ",
    jr_no_trades: "Нет сделок, соответствующих условиям фильтра. Попробуйте изменить параметры.",
    jr_log_new_trade: "РЕГИСТРАЦИЯ НОВОЙ СДЕЛКИ",
    jr_symbol: "Символ *",
    jr_asset_class: "Класс активов",
    jr_direction: "Направление",
    jr_entry_price: "Цена входа *",
    jr_exit_price: "Цена выхода *",
    jr_position_size: "Размер позиции *",
    jr_stop_loss: "Стоп-лосс (Опционально)",
    jr_take_profit: "Тейк-профит (Опционально)",
    jr_strategy_playbook: "Стратегия по шаблону",
    jr_trading_style: "Стиль торговли",
    jr_intraday: "Внутридневная торговля (Day Trading)",
    jr_swing: "Свинг-трейдинг (Swing Trading)",
    jr_intraday_desc: "Быстрые входы и выходы в рамках одной торговой сессии. Фокус на высокой ликвидности, импульсе рынка и строгом соблюдении дневного лимита потерь.",
    jr_swing_desc: "Удержание позиций от нескольких дней до нескольких недель. Фокус на среднесрочных трендах, рыночных циклах, более широких стопах и долгосрочном терпении.",
    jr_entry_timestamp: "Время входа",
    jr_exit_timestamp: "Время выхода",
    jr_broker_account: "Брокерский счет",
    jr_emotion_before: "Эмоция до",
    jr_emotion_after: "Эмоция после",
    jr_slippage_fees: "Проскальзывание/Комиссии ($)",
    jr_commissions: "Комиссия брокера ($)",
    jr_confidence: "Уверенность (1-5)",
    jr_execution_rating: "Оценка исполнения (1-5)",
    jr_visual_setup: "Детали сетапа",
    jr_psych_mistakes: "Выявленные психологические ошибки",
    jr_notes_reflections: "Заметки и размышления",
    jr_actionable_lesson: "Практический извлеченный урок",
    jr_tags_comma: "Теги (через запятую)",
    jr_screenshot: "Скриншот сделки",
    jr_upload_screenshot: "Загрузить скриншот",
    jr_drag_screenshot: "Перетащите изображение скриншота (или нажмите для выбора)",
    jr_remove_screenshot: "Удалить скриншот",
    jr_cancel: "Отмена",
    jr_save_trade: "Сохранить лог сделки",
    jr_import_title: "ИМПОРТ ЖУРНАЛА БРОКЕРА (CSV)",
    jr_import_desc: "Выберите файл вашего брокера (выгрузки TradeZella, Binance, Bybit, Tradovate, Interactive Brokers Excel) или используйте авто-маппер.",
    jr_detected_formats: "Обнаруженные форматы",
    jr_drag_drop: "перетащите файл экспорта брокера сюда",
    jr_supports: "поддерживает .csv, .xlsx",
    jr_simulate_import: "Симулировать импорт",
    jr_parsing: "Парсинг логов брокера... сопоставление параметров",
    jr_import_success: "✓ Импорт успешно завершен! 2 новые сделки интегрированы.",
    jr_import_ready: "Готово к импорту",
    jr_confirm_import: "Подтвердить импорт",
    jr_clear: "Очистить",
    jr_invalid_file: "Некорректный файл",

    // Candle Replay
    rp_title: "ИНТЕРАКТИВНЫЙ СИМУЛЯТОР СВЕЧЕЙ",
    rp_subtitle: "Прокручивайте исторические тики свеча за свечой для аудита дисциплины",
    rp_select_trade: "Выберите сделку для симуляции",
    rp_no_trades: "Сделки еще не записаны. Сначала добавьте сделку в Журнал сделок!",
    rp_trade_specs: "Спецификации сделки",
    rp_specs_direction: "Направление",
    rp_specs_entry: "Цена входа",
    rp_specs_exit: "Цена выхода",
    rp_specs_pnl: "Реализованный PnL",
    rp_specs_rr: "Достигнутый R:R",
    rp_specs_stop: "Стоп-лосс",
    rp_specs_target: "Тейк-профит",
    rp_specs_strategy: "Стратегия",
    rp_specs_emotions: "Эмоции",
    rp_specs_notes: "Заметки по исполнению",
    rp_controls: "Управление симулятором",
    rp_ctrl_prev: "Предыдущая",
    rp_ctrl_play: "Авто-старт",
    rp_ctrl_pause: "Пауза",
    rp_ctrl_next: "След. свеча",
    rp_ctrl_reset: "Сброс",
    rp_ctrl_speed: "Скорость",
    rp_candlestick_chart: "График симуляции свечей",
    rp_chart_legend_entry: "Точка входа",
    rp_chart_legend_exit: "Точка выхода",
    rp_audit_logs: "Логи аудита симулятора",
    rp_audit_start: "Симулятор свечей запущен. Нажмите 'Play' или 'Next', чтобы переключать свечи.",
    rp_audit_entry_alert: "ВНИМАНИЕ: Триггер входа достигнут на индексе свечи",
    rp_audit_exit_alert: "КОНТРОЛЬ ДИСЦИПЛИНЫ: Выход по рынку зафиксирован на индексе свечи",
    rp_audit_complete: "Симуляция завершена. Ознакомьтесь с метриками исполнения выше.",
    rp_audit_consolidation: "Консолидация ценового движения...",

    // Statistics
    st_title: "МНОГОМЕРНАЯ СТАТИСТИКА ТОРГОВЛИ",
    st_subtitle: "Глубокие показатели вашего математического преимущества и распределения",
    st_tab_overview: "Общие метрики",
    st_tab_strategies: "Преимущество стратегий",
    st_tab_timeseries: "Временной анализ",
    st_mathematical_edge: "Разбор математического ожидания",
    st_win_pnl: "Общая прибыль выигрышей",
    st_loss_pnl: "Общий убыток потерь",
    st_win_loss_ratio: "Соотношение Прибыль/Убыток",
    st_expectancy_desc: "Матожидание — это средняя сумма в долларах, которую вы планируете выиграть или проиграть в каждой сделке.",
    st_distribution_by_strategy: "Распределение PnL по стратегиям",
    st_timeframe_distribution: "Распределение PnL по дням недели",
    st_holding_time_title: "Время удержания сделки и корреляция",
    st_efficiency: "Эффективность исполнения",

    // Playbooks
    pl_title: "КОНСТРУКТОР ШАБЛОНОВ СТРАТЕГИЙ",
    pl_subtitle: "Формализуйте жесткие правила входа для предотвращения импульсивных сделок",
    pl_add_strategy: "Создать стратегию",
    pl_target_rr: "Целевой R:R",
    pl_when_to_use: "Когда использовать (Рыночные условия)",
    pl_when_not_to_use: "Когда НЕ использовать (Запрещенные условия)",
    pl_strict_checklist: "Строгий контрольный список входа",
    pl_recent_trades: "Недавние сделки по стратегии",
    pl_no_trades: "По этой стратегии еще нет сделок в журнале",
    pl_form_title: "ПОСТРОЕНИЕ СТРАТЕГИЧЕСКОГО ШАБЛОНА",
    pl_form_name: "Название стратегии",
    pl_form_desc: "Описание / Институциональный тезис",
    pl_form_checklist: "Правила чек-листа (по одному на строку)",
    pl_form_create: "Сохранить стратегию в шаблоне",

    // Trading Plan
    tp_title: "СТРОГИЙ ПРОВЕРЯЕМЫЙ РИСК-ПЛАН",
    tp_subtitle: "Задайте жесткие математические лимиты. Нарушение активирует когнитивно-поведенческий разбор.",
    tp_edit: "Редактировать параметры",
    tp_save: "Зафиксировать лимиты",
    tp_daily_loss: "Дневной лимит потерь",
    tp_max_trades: "Макс. сделок в день",
    tp_banned_triggers: "Запрещенные триггеры действий",
    tp_banned_desc: "Любая сделка из этих категорий считается грубым нарушением торгового плана.",
    tp_entry_rules: "Обязательные критерии входа",
    tp_entry_desc: "Контрольный список, который необходимо проверить перед открытием любой позиции.",
    tp_exit_rules: "Обязательные правила выхода",
    tp_exit_desc: "Правила фиксации целей, стоп-лоссов и аварийного ручного закрытия.",
    tp_morning_prep: "Протокол утренней подготовки к сессии",
    tp_evening_review: "Протокол вечернего разбора сессии",

    // Psychology
    ps_title: "КОГНИТИВНЫЙ И ЭМОЦИОНАЛЬНЫЙ ТРЕКЕР",
    ps_subtitle: "Отслеживайте ментальные метрики для выявления рисков недосыпа или жадности",
    ps_log_button: "Записать когнитивное состояние",
    ps_cognitive_scores: "Показатели когнитивного здоровья и стресса",
    ps_fomo_freq: "Частота FOMO",
    ps_overtrading_score: "Склонность к переторговке",
    ps_sleep_quality: "Качество сна",
    ps_stress_level: "Уровень стресса",
    ps_energy_level: "Уровень энергии",
    ps_revenge_trading: "Зафиксирован тильт/реванш-трейдинг?",
    ps_mental_journal: "Дневной когнитивно-эмоциональный дневник",
    ps_log_title: "ЗАПИСЬ ЕЖЕДНЕВНОГО КОГНИТИВНОГО СОСТОЯНИЯ",
    ps_form_fomo: "Интенсивность позывов FOMO (1-5)",
    ps_form_overtrading: "Импульс к переторговке (1-5)",
    ps_form_fear: "Интенсивность страха (1-5)",
    ps_form_greed: "Интенсивность жадности (1-5)",
    ps_form_patience: "Уровень терпения (1-5)",
    ps_form_sleep: "Продолжительность и глубина сна (1-5)",
    ps_form_stress: "Уровень стресса/тревожности (1-5)",
    ps_form_energy: "Физический тонус/энергия (1-5)",
    ps_form_revenge: "Занимались ли вы сегодня реванш-трейдингом (тильтовали)?",
    ps_form_notes: "Ментальные заметки и эмоциональные размышления",
    ps_form_save: "Сохранить когнитивный лог",

    // Goals
    gl_title: "ПРОВЕРЯЕМЫЕ ЦЕЛИ ДИСЦИПЛИНЫ И ПРИБЫЛИ",
    gl_subtitle: "Создавайте математические цели, автоматически проверяемые базой данных журнала",
    gl_add: "Создать цель для аудита",
    gl_progress: "Обзор прогресса целей",
    gl_form_title: "ПОСТРОЕНИЕ ЦЕЛИ ДЛЯ АУДИТА",
    gl_form_name: "Название цели / ориентира",
    gl_form_type: "Временной интервал",
    gl_form_category: "Категория метрики",
    gl_form_unit: "Единица измерения",
    gl_form_target: "Целевое числовое значение",
    gl_form_current: "Начальное числовое значение",
    gl_form_save: "Активировать трекер цели",

    // AI Coach
    ac_title: "ИИ-НАСТАВНИК РАБОЧЕЙ СТАНЦИИ",
    ac_subtitle: "Интерактивный когнитивно-поведенческий наставник для контроля эмоциональных рисков",
    ac_prompt_fomo: "Проанализировать мое FOMO на основе показателей сна",
    ac_prompt_rules: "Где именно я теряю больше всего прибыли?",
    ac_prompt_patience: "Дай мне чек-лист терпения для работы с TSLA",
    ac_chat_placeholder: "Опишите недавнюю эмоциональную сделку или запросите диагностику рисков...",
    ac_chat_send: "Проконсультироваться",

    // Reviews
    rv_title: "ИИ-ОБЗОРЫ КОГНИТИВНЫХ СЕССИЙ",
    rv_subtitle: "Создавайте структурированные аудиты поведения и результатов с помощью ИИ Gemini",
    rv_card_daily: "Дневной обзор",
    rv_card_weekly: "Недельный аудит",
    rv_card_monthly: "Месячный аудит",
    rv_card_daily_desc: "Объедините сделки и психологические отчеты за день в действенный когнитивный аудит.",
    rv_card_weekly_desc: "Анализируйте дисперсию за несколько дней, утечки стратегий и кривые доходности.",
    rv_card_monthly_desc: "Синтезируйте долгосрочные психологические триггеры, матожидание и правила.",
    rv_generate_btn: "Сгенерировать обзор",
    rv_generating: "Анализ торговых логов... выявление поведенческих паттернов",
    rv_title_report: "ИИ Сгенерированный Отчет",
    rv_report_score: "Оценка Дисциплины",

    // Settings
    se_title: "БЕЗОПАСНЫЕ ИНТЕГРАЦИИ И НАСТРОЙКИ",
    se_subtitle: "Настройте синхронизацию в реальном времени с глобальными мультиброкерскими шлюзами",
    se_supported: "Поддерживаемые брокерские компании",
    se_link_port: "Подключение API порта для",
    se_connected: "СОЕДИНЕНИЕ УСТАНОВЛЕНО",
    se_connected_desc: "ИИ ZellaTrader прослушивает входящие API транзакции на",
    se_connected_desc_end: "Ваши торговые обновления автоматически парсятся и импортируются в Журнал ежедневно в 16:30 EST.",
    se_disconnect: "Отключить порт интеграции",
    se_syncing: "Синхронизация ключей... тестирование рукопожатия сокетов",
    se_token_prompt: "Чтобы безопасно импортировать транзакции, создайте токен API или ключ авторизации 'только для чтения' в консоли вашего брокера.",
    se_api_key: "API Ключ / Client ID",
    se_api_secret: "API Секрет / Secret Salt",
    se_key_warning: "Все ключи шифруются локально с применением протоколов AES-GCM высокого уровня. ZellaTrader запрашивает исключительно права **только для чтения** истории сделок.",
    se_auth_connect: "Аутентифицировать и подключить порт",
    se_lang_section: "Настройки Языка (Language)",
    se_lang_desc: "Выберите предпочитаемый язык интерфейса вашего рабочего пространства",
    se_tradovate_title: "Синхронизация и анализ Tradovate",
    se_tradovate_help: "Как правильно экспортировать файлы Tradovate: В торговой платформе перейдите в раздел Reports -> Orders или Fills. Установите диапазон дат и нажмите Export CSV. Обязательно убедитесь, что столбцы Contract (Контракт), Price (Цена), Qty (Количество) и Timestamp (Время) отображаются и выгружены.",
    se_tradovate_connect: "Подключить API Tradovate",
    se_tradovate_sync_btn: "Синхронизировать и запустить ИИ-аудит",
    se_tradovate_desc: "Подключите ваш торговый аккаунт Tradovate. ИИ Zella автоматически импортирует ваши исполненные ордера (fills), сопоставит входы и выходы по алгоритму FIFO и проведет мгновенный когнитивно-поведенческий аудит вашей дисциплины."
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations["en"]) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("zellatrader_lang");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("zellatrader_lang", lang);
  };

  const t = (key: keyof typeof translations["en"]): string => {
    const dict = translations[language] || translations["en"];
    return dict[key] || translations["en"][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
