export type AssetType = "Stocks" | "Crypto" | "Forex" | "Options" | "Futures";
export type DirectionType = "Long" | "Short";
export type EmotionType = "Calm" | "Greedy" | "Fearful" | "Anxious" | "Excited" | "Disciplined" | "FOMO" | "Frustrated";
export type SessionType = "Morning" | "Afternoon" | "Evening";

export interface Trade {
  id: string;
  ticker: string;
  assetType: AssetType;
  direction: DirectionType;
  entryPrice: number;
  exitPrice: number;
  positionSize: number;
  stopLoss?: number;
  takeProfit?: number;
  entryTime: string; // ISO String or YYYY-MM-DD
  exitTime: string;  // ISO String or YYYY-MM-DD
  fees: number;
  commission: number;
  broker: string;
  strategy: string;
  setup: string;
  tags: string[];
  screenshotUrl?: string;
  rating: number; // 1 to 5 stars
  confidence: number; // 1 to 5
  emotionBefore: EmotionType;
  emotionAfter: EmotionType;
  marketContext: string;
  notes: string;
  mistakes: string[];
  lessons: string[];
  aiReview?: string;
  tradingStyle?: "Intraday" | "Swing";
  pnl?: number; // Calculated: (Exit - Entry) * Size for Long, (Entry - Exit) * Size for Short, minus fees & commission
  rr?: number;  // Risk-Reward ratio achieved
}

export interface Strategy {
  id: string;
  name: string;
  description: string;
  whenToUse: string;
  whenNotToUse: string;
  targetRR: number;
  checklist: string[];
  examples: string[]; // Mock links or notes
}

export interface TradingPlan {
  dailyLossLimit: number;
  maxDailyTrades: number;
  bannedTradeTypes: string[];
  entryRules: string[];
  exitRules: string[];
  morningPrep: { label: string; checked: boolean }[];
  eveningReview: { label: string; checked: boolean }[];
}

export interface PsychologyLog {
  id: string;
  date: string; // YYYY-MM-DD
  fomoFrequency: number; // 1-5
  overtradingScore: number; // 1-5
  revengeTrading: boolean;
  fear: number; // 1-5
  greed: number; // 1-5
  confidence: number; // 1-5
  patience: number; // 1-5
  sleep: number; // 1-5
  stress: number; // 1-5
  energy: number; // 1-5
  notes: string;
  aiPatterns?: string;
}

export interface Goal {
  id: string;
  title: string;
  target: number;
  current: number;
  type: "Daily" | "Weekly" | "Monthly" | "Yearly";
  unit: string; // "$" or "%" or "Trades" or "Score"
  category: "PnL" | "Trades" | "WinRate" | "Discipline";
  completed: boolean;
}

export interface ChatMessage {
  id: string;
  sender: "user" | "ai";
  text: string;
  timestamp: string;
}

export interface AIReviewReport {
  id: string;
  type: "Session" | "Weekly" | "Monthly";
  date: string;
  title: string;
  pnl: number;
  tradesCount: number;
  winRate: number;
  score: number; // 1-100
  content: string; // markdown content generated by Gemini
  bullets?: string[];
}

export interface Candlestick {
  time: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}
